name: Trigger GitHub Pages Deployment

# 触发条件：当 prices 分支有推送时
on:
  push:
    branches: [prices]
  # 允许手动触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  actions: write

jobs:
  trigger-pages-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages deployment
        run: |
          echo "Prices branch updated, triggering GitHub Pages deployment..."

          # 使用 GitHub API 触发 Pages 重新部署
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds

          echo "GitHub Pages deployment triggered successfully!"

      - name: Wait and verify deployment
        run: |
          echo "Waiting 30 seconds for deployment to start..."
          sleep 30

          # 检查最新的 Pages 部署状态
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds \
            | jq -r '.[0] | "Latest build status: \(.status), created at: \(.created_at)"'
