name: Run get_prices.py and commit changes

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 时间 00:00 执行
  workflow_dispatch: # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # 使用你需要的 Python 版本

      - name: Run get_prices.py
        env:
          SILICONFLOW_API_KEY: ${{ secrets.SILICONFLOW_API_KEY }}
        run: |
          python get_prices.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add oneapi_prices.json siliconflow_models.json
          git commit -m "Auto-update price and model data"
          git push origin master
